Doxygen with github: ksf::ksComponent Class Reference
ksf::ksComponent Class Reference
Base component class.
#include <ksComponent.h>
Public Member Functions
virtual const std::size_t getInstanceType () const
Retrieves type ID of the object.
virtual bool isA (const std::size_t id) const
Checks whether object is of given type.
virtual bool init (ksApplication *app)
Initializes component.
virtual bool loop (ksApplication *app)
Handles component loop logic, called from application loop.
virtual bool postInit (ksApplication *app)
Method called after component initialization, used to setup references to other components.
Public Member Functions inherited from ksf::ksRtti
virtual ~ksRtti ()=default
Destructor.
template<typename TType >
TType * as ()
Tries to cast object to the type provided as a template parameter.
template<typename TType >
const TType * as () const
Tries to cast object to the type provided as a template parameter (const version).
Static Public Member Functions
static const std::size_t getClassType ()
Protected Attributes
ksComponentState::TYPE componentState { ksComponentState::NotInitialized }
Holds current state of the component.
Friends
class ksApplication
Detailed Description
Base component class.
A component is a part of the application that can be configured and managed by the application. As it uses ksRtti, it must include KSF_RTTI_DECLARATIONS for proper initialization.
Member Function Documentation
getInstanceType()
virtual const std::size_t ksf::ksComponent::getInstanceType () const inline virtual
Retrieves type ID of the object.
Returns
Object type ID.
Implements ksf::ksRtti.
Reimplemented in ksf::comps::ksConfigProvider, ksf::comps::ksDevicePortal, ksf::comps::ksDevStatMqttReporter, ksf::comps::ksLed, ksf::comps::ksMqttConfigProvider, ksf::comps::ksMqttConnector, ksf::comps::ksResetButton, ksf::comps::ksWifiConfigurator, and ksf::comps::ksWifiConnector.
Referenced by ksf::ksApplication::addComponent(), ksf::ksApplication::findComponent(), and ksf::ksApplication::findComponents().
init()
bool ksf::ksComponent::init (ksApplication * app) virtual
Initializes component.
Parameters
app Pointer to the parent ksApplication.
Returns
True on success, false on fail.
Reimplemented in ksf::comps::ksDevicePortal, ksf::comps::ksLed, ksf::comps::ksMqttConnector, ksf::comps::ksResetButton, ksf::comps::ksWifiConfigurator, and ksf::comps::ksWifiConnector.
Referenced by ksf::comps::ksMqttConnector::init().
isA()
virtual bool ksf::ksComponent::isA (const std::size_t id) const inline virtual
Checks whether object is of given type.
Parameters
id Type ID to check against.
Returns
True if object is of given type, otherwise false.
Reimplemented from ksf::ksRtti.
Reimplemented in ksf::comps::ksConfigProvider, ksf::comps::ksDevicePortal, ksf::comps::ksDevStatMqttReporter, ksf::comps::ksLed, ksf::comps::ksMqttConfigProvider, ksf::comps::ksMqttConnector, ksf::comps::ksResetButton, ksf::comps::ksWifiConfigurator, and ksf::comps::ksWifiConnector.
loop()
bool ksf::ksComponent::loop (ksApplication * app) virtual
Handles component loop logic, called from application loop.
Parameters
app Pointer to the parent ksApplication.
Returns
True on success, false on fail.
Reimplemented in ksf::comps::ksDevicePortal, ksf::comps::ksDevStatMqttReporter, ksf::comps::ksLed, ksf::comps::ksMqttConnector, ksf::comps::ksResetButton, ksf::comps::ksWifiConfigurator, and ksf::comps::ksWifiConnector.
postInit()
bool ksf::ksComponent::postInit (ksApplication * app) virtual
Method called after component initialization, used to setup references to other components.
Parameters
app Pointer to the parent ksApplication.
Returns
True on success, false on fail.
Reimplemented in ksf::comps::ksDevicePortal, ksf::comps::ksDevStatMqttReporter, ksf::comps::ksMqttConnector, and ksf::comps::ksWifiConfigurator.
The documentation for this class was generated from the following files:
src/ksf/ksComponent.h
src/ksf/ksComponent.cpp