Doxygen with github: ksf::comps::ksLed Class Reference
ksf::comps::ksLed Class Reference
Public Member Functions
virtual const size_t getInstanceType () const
This function is used to get type ID of object.
virtual bool isA (const size_t id) const
This function is used to check if object is of given type.
ksLed (uint8_t pin, bool activeLow=false, bool driveAsPushPull=false)
Constructs LED object, assigning passed pin number.
bool init (ksApplication *owner) override
Initializes LED component.
bool loop (ksApplication *app) override
Executes LED component logic.
void setBlinking (uint32_t blinkIntervalMs, uint32_t blinkLoops=0)
Sets LED blinking state.
bool isBlinking () const
Returns whether LED is currently blinking.
bool isEnabled () const
Returns whether LED is enabled.
void setEnabled (bool enabled)
Enables or disables LED.
void setDriveAsPushPull (bool driveAsPushPull)
Enables or disables push/pull driving mode.
uint8_t getPin () const
Returns pin number assigned to LED.
virtual ~ksLed ()
Destructor, disables LED and restores INPUT pin state.
Public Member Functions inherited from ksf::ksComponent
virtual bool postInit (ksApplication *app)
Method called after component initialization.
Public Member Functions inherited from ksf::ksRtti
template<typename TType >
TType * as ()
This function is used to cast object to given type.
template<typename TType >
const TType * as () const
This function is used to const cast object to given type.
Static Public Member Functions
static const size_t getClassType ()
Static Public Member Functions inherited from ksf::ksComponent
static const size_t getClassType ()
Protected Attributes
uint8_t pin {0}
Pin number assigned to LED.
uint32_t lastBlinkTimeMs {0}
Last time LED state was toggled (milliseconds).
uint32_t blinkIntervalMs {0}
Time in ms between LED state toggle (0 to disable blinking).
uint32_t blinkLoops {0}
Number of loops (0 for infinite loop).
bool driveAsActiveLow: 1 { false }
True if LED should be active low, otherwise false.
bool driveAsPushPull: 1 { false }
True if LED should be driven as push-pull, otherwise false.
Protected Attributes inherited from ksf::ksComponent
ksComponentState::TYPE componentState { ksComponentState::NotInitialized }
Constructor & Destructor Documentation
ksLed()
ksf::comps::ksLed::ksLed (uint8_t pin, bool activeLow = false, bool driveAsPushPull = false)
Constructs LED object, assigning passed pin number.
Parameters
pin Pin number assigned to LED
activeLow True if LED should be active low, otherwise false
driveAsPushPull True if LED should be driven as push-pull, otherwise false
Member Function Documentation
getInstanceType()
virtual const size_t ksf::comps::ksLed::getInstanceType () const inline virtual
This function is used to get type ID of object.
Returns
Type ID.
Reimplemented from ksf::ksComponent.
getPin()
uint8_t ksf::comps::ksLed::getPin () const inline
Returns pin number assigned to LED.
Returns
Pin number assigned to LED.
References pin.
init()
bool ksf::comps::ksLed::init (ksApplication * owner) override virtual
Initializes LED component.
Parameters
owner Pointer to ksApplication object that owns this component
Returns
True if init succedeed, otherwise false.
Reimplemented from ksf::ksComponent.
References driveAsPushPull, pin, and setEnabled().
isA()
virtual bool ksf::comps::ksLed::isA (const size_t id) const inline virtual
This function is used to check if object is of given type.
Parameters
id Type ID.
Returns
True if object is of given type, otherwise false.
Reimplemented from ksf::ksComponent.
isBlinking()
bool ksf::comps::ksLed::isBlinking () const
Returns whether LED is currently blinking.
Returns
True if LED is currently blinking, otherwise false.
References blinkIntervalMs.
isEnabled()
bool ksf::comps::ksLed::isEnabled () const
Returns whether LED is enabled.
Returns
True if LED is enabled, otherwise false.
References driveAsActiveLow, and pin.
Referenced by loop(), and setDriveAsPushPull().
loop()
bool ksf::comps::ksLed::loop (ksApplication * app) override virtual
Executes LED component logic.
Returns
True if everything is okay, otherwise false to break application logic.
Reimplemented from ksf::ksComponent.
References blinkIntervalMs, blinkLoops, isEnabled(), lastBlinkTimeMs, setBlinking(), and setEnabled().
setBlinking()
void ksf::comps::ksLed::setBlinking (uint32_t blinkIntervalMs, uint32_t blinkLoops = 0)
Sets LED blinking state.
Parameters
blinkIntervalMs Time in ms between LED state toggle (0 to disable blinking)
blinkLoops Number of loops (0 for infinite loop)
References blinkIntervalMs, blinkLoops, lastBlinkTimeMs, and setEnabled().
Referenced by loop().
setDriveAsPushPull()
void ksf::comps::ksLed::setDriveAsPushPull (bool driveAsPushPull)
Enables or disables push/pull driving mode.
Parameters
driveAsPushPull True if LED should be driven as push-pull, otherwise false
References driveAsPushPull, isEnabled(), pin, and setEnabled().
setEnabled()
void ksf::comps::ksLed::setEnabled (bool enabled)
Enables or disables LED.
Parameters
enabled True to enable LED, false to disable.
References driveAsActiveLow, driveAsPushPull, and pin.
Referenced by init(), loop(), ksf::comps::ksWiFiConfigurator::postInit(), setBlinking(), setDriveAsPushPull(), and ~ksLed().
The documentation for this class was generated from the following files:
src/ksf/comp/ksLed.h
src/ksf/comp/ksLed.cpp