Doxygen with github: ksf::comps::ksWifiConfigurator Class Reference
ksf::comps::ksWifiConfigurator Class Reference
A component that manages AP-based configuration.
#include <ksWifiConfigurator.h>
Public Member Functions
virtual const std::size_t getInstanceType () const
Retrieves type ID of the object.
virtual bool isA (const std::size_t id) const
Checks whether object is of given type.
ksWifiConfigurator ()
Constructs WiFi configurator object.
ksWifiConfigurator (std::string devicePrefixName)
Constructs WiFi configurator object.
virtual ~ksWifiConfigurator ()
Destructs WiFi configurator component.
bool loop (ksApplication *app) override
Handles ksWifiConfigurator logic.
bool init (ksApplication *app) override
Implements ksWifiConfigurator initialization logic.
bool postInit (ksApplication *app) override
Implements ksWifiConfigurator post-initialization logic.
Public Member Functions inherited from ksf::ksRtti
virtual ~ksRtti ()=default
Destructor.
template<typename TType>
TType * as ()
Tries to cast object to the type provided as a template parameter.
template<typename TType>
const TType * as () const
Tries to cast object to the type provided as a template parameter (const version).
Static Public Member Functions
static const std::size_t getClassType ()
Static Public Member Functions inherited from ksf::ksComponent
static const std::size_t getClassType ()
Protected Member Functions
void handlePeriodicTasks ()
Handles periodic tasks like WiFi management.
Protected Attributes
ksApplication * app {nullptr}
Pointer to ksApplication object that owns this component.
std::string deviceName
Device name (prefix).
misc::ksSimpleTimer configTimeout {120 * 1000}
Timeout for captive portal in ms.
misc::ksSimpleTimer periodicTasksTimeout {1000}
Timeout for loop in ms.
Protected Attributes inherited from ksf::ksComponent
ksComponentState::TYPE componentState { ksComponentState::NotInitialized }
Detailed Description
A component that manages AP-based configuration.
This component handles the Device Portal, allowing users to configure WiFi and MQTT credentials, as well as custom application-specific parameters implemented via the ksConfigProvider interface.
Constructor & Destructor Documentation
ksWifiConfigurator()
ksf::comps::ksWifiConfigurator::ksWifiConfigurator (std::string devicePrefixName)
Constructs WiFi configurator object.
Parameters
devicePrefixName Device prefix name, will be used in AP (DEVPREFIX-112ACB84) and hostname
References deviceName.
Member Function Documentation
getInstanceType()
virtual const std::size_t ksf::comps::ksWifiConfigurator::getInstanceType () const inline virtual
Retrieves type ID of the object.
Returns
Object type ID.
Reimplemented from ksf::ksComponent.
References ksWifiConfigurator().
init()
bool ksf::comps::ksWifiConfigurator::init (ksApplication * app) override virtual
Implements ksWifiConfigurator initialization logic.
Parameters
app Pointer to ksApplication object that owns this component
Returns
True on success, false on fail.
Reimplemented from ksf::ksComponent.
References app, and deviceName.
isA()
virtual bool ksf::comps::ksWifiConfigurator::isA (const std::size_t id) const inline virtual
Checks whether object is of given type.
Parameters
id Type ID to check against.
Returns
True if object is of given type, otherwise false.
Reimplemented from ksf::ksComponent.
loop()
bool ksf::comps::ksWifiConfigurator::loop (ksApplication * app) override virtual
Handles ksWifiConfigurator logic.
It starts and handles Device Portal, where the user can configure the device (that means WiFi or MQTT credential as well as custom defined device parameters).
Parameters
app Pointer to ksApplication object that owns this component.
Returns
True if loop succedeed, otherwise false.
Reimplemented from ksf::ksComponent.
References app, configTimeout, handlePeriodicTasks(), and periodicTasksTimeout.
postInit()
bool ksf::comps::ksWifiConfigurator::postInit (ksApplication * app) override virtual
Implements ksWifiConfigurator post-initialization logic.
Parameters
app Pointer to ksApplication object that owns this component
Returns
True on success, false on fail.
Reimplemented from ksf::ksComponent.
References app, and ksf::comps::ksLed::setEnabled().
The documentation for this class was generated from the following files:
src/ksf/comp/ksWifiConfigurator.h
src/ksf/comp/ksWifiConfigurator.cpp