name: build-examples
on:
  workflow_dispatch:
#  push:
#    paths:
#      - 'firmware/**'
jobs:
  build-with-pio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build examples with PlatformIO
      run: |
        cd examples
        pio upgrade
        cd basic-config
        pio run
    - name: Deploy firmware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: basoc-comfig-${{ github.run_id }}
        path: firmware/.pio/build/esp8266dev/firmware.bin
