name: Doxygen Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@85e6279cec87321a52edac9c87bce653a07cf6c2
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "."
    - name: Deploy
      uses: peaceiris/actions-gh-pages@aa83d0c2cfc3d813560e13068d3152aa21490171
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
