name: Validate commit messages
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages in PR
        run: |
          set -euo pipefail
          base=${{ github.event.pull_request.base.sha }}
          head=${{ github.event.pull_request.head.sha }}
          echo "Checking commits from $base..$head"
          ./scripts/validate-commit-messages.sh $base $head
